/qa.debian.org/popcon.php?package=ethtool">V:94, I:266</a>
                  </td>
                  <td style="text-align: left">
                    <a class="ulink" href="http://packages.qa.debian.org/e/ethtool.html">372</a>
                  </td>
                  <td style="text-align: left">
    , ,
    </td>
                  <td style="text-align: left">
    display or change Ethernet device settings
    </td>
                </tr>
                <tr>
                  <td style="text-align: left">
                    <a class="ulink" href="http://packages.debian.org/sid/iputils-ping">
                <code class="literal">iputils-ping</code>
              </a>
                  </td>
                  <td style="text-align: left">
                    <a class="ulink" href="http://qa.debian.org/popcon.php?package=iputils-ping">V:257, I:997</a>
                  </td>
                  <td style="text-align: left">
                    <a class="ulink" href="http://packages.qa.debian.org/i/iputils-ping.html">111</a>
                  </td>
